#define HAL_ERROR_I2S_TRANSMIT 	0
#define HAL_ERROR_I2S_RECEIVE 	1
#define HAL_ERROR_I2S_INIT  	2
#define HAL_ERROR_I2C_TRANSMIT 	3
#define HAL_ERROR_I2C_RECEIVE 	4
#define HAL_ERROR_I2C_INIT  	5
#define HAL_ERROR_UART_TRANSMIT 6
#define HAL_ERROR_UART_RECEIVE 	7
#define HAL_ERROR_UART_INIT  	8
#define HAL_ERROR_UART_CALLBACK 9
#define HAL_ERROR_TIMER_INIT 	10
#define HAL_ERROR_ENCODER_INIT  11

#define HAL_ERROR_SYSCLOCK_INIT 12
