#include <stdio.h>
#include "../../../test-tools/c/fopnchk/fopnchk.h"
#include <gn_ref.h>
#include <modules.h>
#include "../c/empty_module_template.h" // remove this line when you have inserted empty_module_template in modules.h
#include "filenames.h"

#define BLOCKSIZE 64

#ifdef PREPARE_KEIL_DBGINPUT
// helper procedure.
static int get_channel(int _id) {
    static int xxx[8] = {8,1,2,3,4,5,6,7};
    return xxx[_id&7];
}
// create mod_openfile.ini
// align a filenames of the testvectors in debug.ini and filenames.h
void keil_dbg_filenames(const char *outfile) {
    FILE *fo = fopen(outfile, "wb");
    if (fo) {
        fprintf(fo, 
        "/* µVision V5.27 debug script - autogenerated */\n\n"
        "/* The function opens and redirects the ITM channel output(from 1 to 8) in file */\n\n"
        "func void OpenFile(int _fileId, int _fileState) {\n"
        "    switch(_fileId) {\n"
                    );
        for(int i=0; i<DBG_FILES_COUNT; i++) {
            if (file_names[i]==0 || *file_names[i] == 0) {
                break;
            }
            fprintf(fo,
                "        case %i:\n"
                "            if (_fileState) { exec(\"ITMLOG %i >%s\"); }\n"
                "            else { exec(\"ITMLOG %i >>%s\"); }\n"
                "            break;\n"
                , i+1
                , get_channel(i+1), file_names[i]
                , get_channel(i+1), file_names[i]
            );
        }
        fprintf(fo,
            "        default:\n"
            "            break;\n"
            "    }\n}\n"
        );
        fclose(fo);
    }
}
#else
void keil_dbg_filenames(const char *outfile) {
    (void)outfile;
}
#endif

int main() {
    keil_dbg_filenames("mod_openfile.ini");
    printf("\n");
    printf("-------------\n");
    printf("-- TESTING --\n");
    printf("-------------\n");  
    FILE *fid = fopnchk("../../../test-tools/signals/headset_rx_in.f32","rb");
    char filename[260];
    strcpy(filename,"testvectors/c/");
    sscanf(file_names[0],"testvectors/stm32/%s", &filename[sizeof("testvectors/c/")-1]);
    FILE *fo0 = fopnchk(filename,"wb");
    float inbuf[BLOCKSIZE];
    t_empty_module_template_data empty_module_template;
    int init_code = empty_module_template_init(&empty_module_template, BLOCKSIZE);
    if (init_code!=0) printf("Init error code: %i\n", init_code);
    while (fread(inbuf, sizeof(float), BLOCKSIZE, fid) == BLOCKSIZE) {
        empty_module_template_apply(&empty_module_template, inbuf);
        fwrite(&empty_module_template.output, sizeof(float), BLOCKSIZE, fo0);
    }
    fopnchk_close_all();
    return 0;
}
